# Generated by Django 5.1.5 on 2025-01-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='type',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Section', 'Section'), ('Term', 'Term'), ('Article', 'Article'), ('Example', 'Example'), ('Theorem', 'Theorem')], default='Unknown', max_length=20),
        ),
    ]
