# Generated by Django 5.1.5 on 2025-01-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_app', '0002_term_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='type',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('Section', 'Section'), ('Term', 'Term'), ('Article', 'Article'), ('Example', 'Example'), ('Theorem', 'Theorem')], default='Unspecified', max_length=20),
        ),
    ]
